r"""
Встраивает admin_lessons.json / admin_contents.json / admin_regulation.json
в upload_academy/index.html. Ищет маркер END_OF_LESSON_CONTENTS_MARKER и
вставляет константы сразу после него.

Если маркер не найден — вставляет после `const LESSON_CONTENTS = [ ... ];`.
"""

import json
import re
from pathlib import Path

ROOT = Path(r"C:\Users\Madiyar\Desktop\клод проекты\Атырау")
HTML = ROOT / "upload_academy" / "index.html"

lessons = json.loads((ROOT / "admin_lessons.json").read_text(encoding="utf-8"))
contents = json.loads((ROOT / "admin_contents.json").read_text(encoding="utf-8"))
regulation = json.loads((ROOT / "admin_regulation.json").read_text(encoding="utf-8"))

def js_escape_template(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

# --- LESSONS_ADMIN ---
lessons_js_lines = ["const LESSONS_ADMIN = ["]
for l in lessons:
    title = l["title"].replace("'", "\\'")
    desc = l["desc"].replace("'", "\\'")
    task = l["task"].replace("'", "\\'")
    lessons_js_lines.append(
        f"  {{ module:{l['module']}, title:'{title}', desc:'{desc}', task:'{task}' }},"
    )
lessons_js_lines.append("];")
lessons_js = "\n".join(lessons_js_lines)

# --- LESSON_CONTENTS_ADMIN ---
contents_body = "[\n  " + ",\n\n  ".join(
    "`" + js_escape_template(c) + "`" for c in contents
) + "\n]"
contents_js = f"const LESSON_CONTENTS_ADMIN = {contents_body};"

# --- ADMIN_REGULATION ---
reg_js = f"const ADMIN_REGULATION = `{js_escape_template(regulation['html'])}`;"

# --- ADMIN_MODULES ---
admin_modules = [
    {"title": "Философия и мышление",     "icon": "🧠", "desc": "Основа сервисного подхода"},
    {"title": "Стандарты работы",         "icon": "📋", "desc": "Регламенты и ежедневный ритм"},
    {"title": "Работа с клиентами",       "icon": "🤝", "desc": "От встречи до Вау-эффекта"},
    {"title": "Продажи и выручка",        "icon": "💰", "desc": "Влияние администратора на кассу"},
    {"title": "Управление процессами",    "icon": "⚙️", "desc": "KPI, сбои, повторные визиты"},
]
mod_lines = ["const ADMIN_MODULES = ["]
for m in admin_modules:
    title = m["title"].replace("'", "\\'")
    desc = m["desc"].replace("'", "\\'")
    mod_lines.append(f"  {{ title:'{title}', desc:'{desc}', icon:'{m['icon']}' }},")
mod_lines.append("];")
mod_js = "\n".join(mod_lines)

# TOTAL_ADMIN_LESSONS
total_js = f"const TOTAL_ADMIN_LESSONS = {len(lessons)};"

BLOCK = "\n\n// === ADMIN ACADEMY DATA (auto-generated by embed_admin_academy.py) ===\n" \
        + total_js + "\n\n" + mod_js + "\n\n" + lessons_js + "\n\n" + contents_js + "\n\n" + reg_js + "\n"

html = HTML.read_text(encoding="utf-8")

# Ищем маркер после LESSON_CONTENTS
marker = "const LESSON_CONTENTS = ["
pos = html.find(marker)
if pos < 0:
    raise SystemExit("LESSON_CONTENTS не найден")
end = html.find("];", pos)
end += 2  # after "];"

# Удаляем предыдущую вставку админского блока (если пере-запуск)
existing = re.search(
    r"\n\n// === ADMIN ACADEMY DATA \(auto-generated by embed_admin_academy\.py\) ===[\s\S]*?"
    r"const ADMIN_REGULATION = `[\s\S]*?`;\s*",
    html,
)
if existing:
    html = html[:existing.start()] + html[existing.end():]
    # Пересчитаем end после удаления
    pos = html.find(marker)
    end = html.find("];", pos) + 2

new_html = html[:end] + BLOCK + html[end:]
HTML.write_text(new_html, encoding="utf-8")

print(f"Встроено:")
print(f"  TOTAL_ADMIN_LESSONS = {len(lessons)}")
print(f"  ADMIN_MODULES: {len(admin_modules)}")
print(f"  LESSONS_ADMIN: {len(lessons)}")
print(f"  LESSON_CONTENTS_ADMIN: {len(contents)} шт., {sum(len(c) for c in contents)} chars total")
print(f"  ADMIN_REGULATION: {len(regulation['html'])} chars")
print(f"Файл теперь: {HTML.stat().st_size} bytes")
